In [12]:
import pandas as pd

data= pd.read_csv("bmw.csv",squeeze=True)

data


data.drop_duplicates(subset=["engineSize"],keep="first",inplace=True)

data.sort_index()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,5 Series,2014,11200,Automatic,67068,Diesel,125,57.6,2.0
2,5 Series,2016,16000,Automatic,62794,Diesel,160,51.4,3.0
3,1 Series,2017,12750,Automatic,26676,Diesel,145,72.4,1.5
32,i3,2016,17100,Automatic,25269,Other,0,470.8,0.6
66,1 Series,2016,12500,Manual,24111,Petrol,145,47.1,1.6
360,M5,2019,72000,Semi-Auto,3545,Petrol,145,24.1,4.4
621,i3,2017,19998,Automatic,41949,Hybrid,140,470.8,0.0
7284,5 Series,2002,1595,Automatic,115000,Petrol,325,28.5,2.2
7285,X3,2004,3495,Automatic,100000,Petrol,330,23.7,2.5
7559,M3,2010,17750,Manual,79000,Petrol,570,22.8,4.0
7562,M3,2004,14950,Automatic,55000,Petrol,315,23.3,3.2
8835,i3,2015,17400,Automatic,29465,Electric,0,470.8,1.0
9229,M6,2006,12495,Semi-Auto,89000,Petrol,570,19.1,5.0
9555,Z3,1999,3995,Manual,74282,Petrol,245,35.3,1.9
9585,7 Series,2017,52950,Automatic,22000,Petrol,150,22.1,6.6
9625,5 Series,1996,5995,Automatic,36000,Petrol,270,26.4,2.8
9856,5 Series,2002,6990,Automatic,78316,Petrol,325,23.7,3.5